import { ComboBox, ScrollView } from "std-widgets.slint";
export struct ReturnRowData {
    time: string,
    values: [float],
}
export component ReturnMatrix {
    property <color> bg-increase: #58af26;
    property <color> bg-decrease: #c04c4c;
    property <color> bg-avg: #777;
    property <color> text-item: #fff;
    in property <string> return-type: "daily";
    in property <string> selected-month: "January";
    property <length> width-column-monthly: 90px;
    property <length> width-column-daily: 60px;
    property <[ReturnRowData]> monthly_return_data: [
        { time: "2025", values: [-1.28, -31.95, -18.69, -1.56, 40.84, -1.49, 48.77, 0.43, -3.46, 47.21, -9.75, 0.0] },
        { time: "2024", values: [-32.44, -19.77, -27.99, 2.64, 24.65, -22.11, 8.96, 13.01, 8.0, 7.0, -8.0, 70.0] },
        { time: "2023", values: [-26.89, -24.16, -16.88, -44.79, 56.26, -7.33, -14.49, -17.67, 5.0, 6.0, 3.0, 2.0] },
        { time: "2022", values: [78.51, 8.41, 34.74, -2.31, -2.31, 35.62, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0] },
        { time: "2021", values: [39.86, 21.01, 38.98, 55.04, 12.21, 53.34, 25.39, 11.0, 12.0, 13.0, 14.0, 15.0] },
        { time: "2020", values: [0.0, 0.0, 24.11, 17.97, 16.31, 92.86, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0] },
        { time: "Average", values: [9.29, -7.09, 5.38, 4.17, 24.99, 25.15, 11.77, 1.63, 4.42, 13.20, 1.08, 16.50]}
    ];

    property <[ReturnRowData]> daily_return_data: [
        { time: "2025", values: [-1.28, -31.95, -18.69, -1.56, 40.84, -1.49, 48.77, 0.43, -3.46, 47.21, -9.75, 0.0, 2.1, -0.5, 1.2, 0.8, -1.0, 0.7, 1.5, -0.2, 0.9, 1.0, -0.3, 0.5, 0.6, -0.4, 0.2, 0.3, 0.4, 0.0, 1.0] },
        { time: "2024", values: [-32.44, -19.77, -27.99, 2.64, 24.65, -22.11, 8.96, 13.01, 8.0, 7.0, -8.0, 70.0, 1.2, 0.5, -0.3, 0.7, 0.0, -0.2, 0.9, 1.5, -0.7, 0.3, 1.0, -1.2, 0.6, 0.8, -0.4, 0.2, 0.5, -0.1, 1.3] },
        { time: "2023", values: [-26.89, -24.16, -16.88, -44.79, 56.26, -7.33, -14.49, -17.67, 5.0, 6.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, -1.2, 0.6, 0.8, -0.4, 0.2, 0.5, -0.1, 1.3, -0.6, -0.4, 0.8, 1.0, 0.3] },
        { time: "2022", values: [78.51, 8.41, 34.74, -2.31, -2.31, 35.62, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 1.0, -1.2, 0.6, 0.8, -0.4, 0.2, 0.5, -0.1, 1.3, -0.6, -0.4, 0.8, 1.0, 0.3, -0.7, 0.4, 0.6, -0.5, 1.1] },
        { time: "2021", values: [39.86, 21.01, 38.98, 55.04, 12.21, 53.34, 25.39, 11.0, 12.0, 13.0, 14.0, 15.0, 0.2, 0.5, -0.1, 1.3, -0.6, -0.4, 0.8, 1.0, 0.3, -0.7, 0.4, 0.6, -0.5, 1.1, 0.2, -0.4, 0.6, -0.2, 1.2] },
        { time: "2020", values: [0.0, 0.0, 24.11, 17.97, 16.31, 92.86, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 0.4, -0.3, 1.5, 0.9, -0.6, 2.0, -1.1, 0.5, 1.1, -0.3, 0.7, 0.0, -0.2, 0.9, 1.5, -0.7, 0.3, 1.0, -1.2] },
        { time: "Average", values: [9.29, -7.09, 5.38, 4.17, 24.99, 25.15, 11.77, 1.63, 4.42, 13.20, 1.08, 16.50, 2.1, 3.2, 1.5, 0.8, 2.7, 1.1, 0.9, 2.3, 1.0, 0.5, 1.2, 2.0, 1.7, 0.6, 1.8, 2.2, 1.3, 0.7, 1.0]}
    ];

    property <[ReturnRowData]> quarterly_return_data: [
        { time: "2025", values: [-1.28, -31.95, -18.69, -1.56]},
        { time: "2024", values: [-32.44, -19.77, -27.99, 2.64]},
        { time: "2023", values: [-26.89, -24.16, -16.88, -44.79]},
        { time: "2022", values: [78.51, 8.41, 34.74, -2.31]},
        { time: "2021", values: [39.86, 21.01, 38.98, 55.04]},
        { time: "2020", values: [0.0, 0.0, 24.11, 17.97]},
        { time: "Average", values: [9.29, -7.09, 5.38, 4.17]}
    ];

    property <[ReturnRowData]> weekly_return_data: [
        { time: "2025", values: [1.23, -0.45, 2.34, -1.56, 0.78, 1.67, -2.13, 0.56, 1.89, -0.34, 2.01, -1.22, 0.98, 1.45, -2.34, 0.67, 1.12, -0.89, 2.56, -1.78, 0.34, 1.23, -2.01, 0.56, 1.67, -0.45, 2.34, -1.56, 0.78, 1.67, -2.13, 0.56, 1.89, -0.34, 2.01, -1.22, 0.98, 1.45, -2.34, 0.67, 1.12, -0.89, 2.56, -1.78, 0.34, 1.23, -2.01, 0.56, 1.67, -0.45, 2.34, -1.56]},
        { time: "2024", values: [-1.12, 0.56, -2.34, 1.45, -0.78, 2.13, -1.67, 0.34, -2.01, 1.22, -0.98, 2.34, -1.45, 0.67, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78]},
        { time: "2023", values: [2.01, -1.22, 0.98, -2.34, 1.45, -0.67, 2.56, -1.78, 0.34, -2.01, 1.12, -0.89, 2.56, -1.78, 0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01]},
        { time: "2022", values: [-2.34, 1.45, -0.67, 2.56, -1.78, 0.34, -2.01, 1.12, -0.89, 2.56, -1.78, 0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56]},
        { time: "2021", values: [0.34, -2.01, 1.12, -0.89, 2.56, -1.78, 0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89]},
        { time: "2020", values: [1.12, -0.89, 2.56, -1.78, 0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78, -0.34, 2.01, -1.12, 0.89, -2.56, 1.78]},
        { time: "Average", values: [0.56, -1.23, 1.34, -0.45, 2.01, -1.22, 0.98, 1.45, -2.34, 0.67, 1.12, -0.89, 2.56, -1.78, 0.34, 1.23, -2.01, 0.56, 1.67, -0.45, 2.34, -1.56, 0.78, 1.67, -2.13, 0.56, 1.89, -0.34, 2.01, -1.22, 0.98, 1.45, -2.34, 0.67, 1.12, -0.89, 2.56, -1.78, 0.34, 1.23, -2.01, 0.56, 1.67, -0.45, 2.34, -1.56, 0.78, 1.67, -2.13, 0.56, 1.89, -0.34]}
    ];

    in property <[ReturnRowData]> return_row_data: return-type == "daily" ? daily_return_data : return-type== "monthly" ? monthly_return_data : return-type == "quarterly" ? quarterly_return_data : weekly_return_data;

    property <[string]> monthly_columns: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    property <[string]> daily_jan_columns: ["Jan 1", "Jan 2", "Jan 3", "Jan 4", "Jan 5", "Jan 6", "Jan 7", "Jan 8", "Jan 9", "Jan 10", "Jan 11", "Jan 12", "Jan 13", "Jan 14", "Jan 15", "Jan 16", "Jan 17", "Jan 18", "Jan 19", "Jan 20", "Jan 21", "Jan 22", "Jan 23", "Jan 24", "Jan 25", "Jan 26", "Jan 27", "Jan 28", "Jan 29", "Jan 30", "Jan 31"];
    property <[string]> daily_feb_columns: ["Feb 1", "Feb 2", "Feb 3", "Feb 4", "Feb 5", "Feb 6", "Feb 7", "Feb 8", "Feb 9", "Feb 10", "Feb 11", "Feb 12", "Feb 13", "Feb 14", "Feb 15", "Feb 16", "Feb 17", "Feb 18", "Feb 19", "Feb 20", "Feb 21", "Feb 22", "Feb 23", "Feb 24", "Feb 25", "Feb 26", "Feb 27", "Feb 28", "Feb 29"];
    property <[string]> daily_mar_columns: ["Mar 1", "Mar 2", "Mar 3", "Mar 4", "Mar 5", "Mar 6", "Mar 7", "Mar 8", "Mar 9", "Mar 10", "Mar 11", "Mar 12", "Mar 13", "Mar 14", "Mar 15", "Mar 16", "Mar 17", "Mar 18", "Mar 19", "Mar 20", "Mar 21", "Mar 22", "Mar 23", "Mar 24", "Mar 25", "Mar 26", "Mar 27", "Mar 28", "Mar 29", "Mar 30", "Mar 31"];
    property <[string]> daily_apr_columns: ["Apr 1", "Apr 2", "Apr 3", "Apr 4", "Apr 5", "Apr 6", "Apr 7", "Apr 8", "Apr 9", "Apr 10", "Apr 11", "Apr 12", "Apr 13", "Apr 14", "Apr 15", "Apr 16", "Apr 17", "Apr 18", "Apr 19", "Apr 20", "Apr 21", "Apr 22", "Apr 23", "Apr 24", "Apr 25", "Apr 26", "Apr 27", "Apr 28", "Apr 29", "Apr 30"];
    property <[string]> daily_may_columns: ["May 1", "May 2", "May 3", "May 4", "May 5", "May 6", "May 7", "May 8", "May 9", "May 10", "May 11", "May 12", "May 13", "May 14", "May 15", "May 16", "May 17", "May 18", "May 19", "May 20", "May 21", "May 22", "May 23", "May 24", "May 25", "May 26", "May 27", "May 28", "May 29", "May 30", "May 31"];
    property <[string]> daily_jun_columns: ["Jun 1", "Jun 2", "Jun 3", "Jun 4", "Jun 5", "Jun 6", "Jun 7", "Jun 8", "Jun 9", "Jun 10", "Jun 11", "Jun 12", "Jun 13", "Jun 14", "Jun 15", "Jun 16", "Jun 17", "Jun 18", "Jun 19", "Jun 20", "Jun 21", "Jun 22", "Jun 23", "Jun 24", "Jun 25", "Jun 26", "Jun 27", "Jun 28", "Jun 29", "Jun 30"];
    property <[string]> daily_jul_columns: ["Jul 1", "Jul 2", "Jul 3", "Jul 4", "Jul 5", "Jul 6", "Jul 7", "Jul 8", "Jul 9", "Jul 10", "Jul 11", "Jul 12", "Jul 13", "Jul 14", "Jul 15", "Jul 16", "Jul 17", "Jul 18", "Jul 19", "Jul 20", "Jul 21", "Jul 22", "Jul 23", "Jul 24", "Jul 25", "Jul 26", "Jul 27", "Jul 28", "Jul 29", "Jul 30", "Jul 31"];
    property <[string]> daily_aug_columns: ["Aug 1", "Aug 2", "Aug 3", "Aug 4", "Aug 5", "Aug 6", "Aug 7", "Aug 8", "Aug 9", "Aug 10", "Aug 11", "Aug 12", "Aug 13", "Aug 14", "Aug 15", "Aug 16", "Aug 17", "Aug 18", "Aug 19", "Aug 20", "Aug 21", "Aug 22", "Aug 23", "Aug 24", "Aug 25", "Aug 26", "Aug 27", "Aug 28", "Aug 29", "Aug 30", "Aug 31"];
    property <[string]> daily_sep_columns: ["Sep 1", "Sep 2", "Sep 3", "Sep 4", "Sep 5", "Sep 6", "Sep 7", "Sep 8", "Sep 9", "Sep 10", "Sep 11", "Sep 12", "Sep 13", "Sep 14", "Sep 15", "Sep 16", "Sep 17", "Sep 18", "Sep 19", "Sep 20", "Sep 21", "Sep 22", "Sep 23", "Sep 24", "Sep 25", "Sep 26", "Sep 27", "Sep 28", "Sep 29", "Sep 30"];
    property <[string]> daily_oct_columns: ["Oct 1", "Oct 2", "Oct 3", "Oct 4", "Oct 5", "Oct 6", "Oct 7", "Oct 8", "Oct 9", "Oct 10", "Oct 11", "Oct 12", "Oct 13", "Oct 14", "Oct 15", "Oct 16", "Oct 17", "Oct 18", "Oct 19", "Oct 20", "Oct 21", "Oct 22", "Oct 23", "Oct 24", "Oct 25", "Oct 26", "Oct 27", "Oct 28", "Oct 29", "Oct 30", "Oct 31"];
    property <[string]> daily_nov_columns: ["Nov 1", "Nov 2", "Nov 3", "Nov 4", "Nov 5", "Nov 6", "Nov 7", "Nov 8", "Nov 9", "Nov 10", "Nov 11", "Nov 12", "Nov 13", "Nov 14", "Nov 15", "Nov 16", "Nov 17", "Nov 18", "Nov 19", "Nov 20", "Nov 21", "Nov 22", "Nov 23", "Nov 24", "Nov 25", "Nov 26", "Nov 27", "Nov 28", "Nov 29", "Nov 30"];
    property <[string]> daily_dec_columns: ["Dec 1", "Dec 2", "Dec 3", "Dec 4", "Dec 5", "Dec 6", "Dec 7", "Dec 8", "Dec 9", "Dec 10", "Dec 11", "Dec 12", "Dec 13", "Dec 14", "Dec 15", "Dec 16", "Dec 17", "Dec 18", "Dec 19", "Dec 20", "Dec 21", "Dec 22", "Dec 23", "Dec 24", "Dec 25", "Dec 26", "Dec 27", "Dec 28", "Dec 29", "Dec 30", "Dec 31"];
    property <[string]> quarterly_columns: ["Q1", "Q2", "Q3", "Q4"];
    property <[string]> weekly_columns: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7", "Week 8", "Week 9", "Week 10", "Week 11", "Week 12", "Week 13", "Week 14", "Week 15", "Week 16", "Week 17", "Week 18", "Week 19", "Week 20", "Week 21", "Week 22", "Week 23", "Week 24", "Week 25", "Week 26", "Week 27", "Week 28", "Week 29", "Week 30", "Week 31", "Week 32", "Week 33", "Week 34", "Week 35", "Week 36", "Week 37", "Week 38", "Week 39", "Week 40", "Week 41", "Week 42", "Week 43", "Week 44", "Week 45", "Week 46", "Week 47", "Week 48", "Week 49", "Week 50", "Week 51", "Week 52"];
    
    function get_return_name_columns() -> [string] {
        if (return-type == "daily") {
            if (selected-month == "January") {
                return daily_jan_columns;
            } else if (selected-month == "February") {
                return daily_feb_columns;
            } else if (selected-month == "March") {
                return daily_mar_columns;
            } else if (selected-month == "April") {
                return daily_apr_columns;
            } else if (selected-month == "May") {
                return daily_may_columns;
            } else if (selected-month == "June") {
                return daily_jun_columns;
            } else if (selected-month == "July") {
                return daily_jul_columns;
            } else if (selected-month == "August") {
                return daily_aug_columns;
            } else if (selected-month == "September") {
                return daily_sep_columns;
            } else if (selected-month == "October") {
                return daily_oct_columns;
            } else if (selected-month == "November") {
                return daily_nov_columns;
            } else if (selected-month == "December") {
                return daily_dec_columns;
            } else {
                return [];
            }
        } else if (return-type == "monthly") {
            return monthly_columns;
        } else if (return-type == "quarterly") {
            return quarterly_columns;
        } else {
            return weekly_columns;
        }
    }
    in property <[string]> return_name_columns : get_return_name_columns();
    Rectangle {
        background: #111;
        border-radius: 6px;
        VerticalLayout {
            spacing: 2px;
            HorizontalLayout {
                VerticalLayout {
                    
                    spacing: 2px;
                    Rectangle {height: 36px; width: 90px; background: transparent;
                       Text { text: "Time"; color: root.text-item; font-weight: 700;}
                    }
                    for row[i] in root.return_row_data: Rectangle {
                        height: 36px;
                        width: 90px;
                        background: Math.mod(i, 2) == 0 ? #222 : #181818;
                        Text { text: row.time; color: root.text-item; horizontal-alignment: center; }
                    }
                }
                ScrollView {
                    VerticalLayout {
                        spacing: 2px;
                        // Dòng tiêu đề
                        HorizontalLayout {
                            spacing: 2px;
                            for col in root.return_name_columns: Rectangle { 
                                        width: return-type == "daily" ? root.width-column-daily : root.width-column-monthly; background: transparent;
                                            Text { text: col; color: root.text-item; font-weight: 700; } }
                        }
                        
                        // Dòng dữ liệu
                        for row[i] in root.return_row_data: Rectangle {
                            width: root.return_name_columns.length * 2px + root.return_name_columns.length * (return-type == "daily" ? root.width-column-daily : root.width-column-monthly);
                            height: 36px;
                            background: Math.mod(i, 2) == 0 ? #222 : #181818;
                            HorizontalLayout {
                                spacing: 2px;
                                for value[j] in row.values: Rectangle {
                                    width: return-type == "daily" ? root.width-column-daily : return-type == "monthly" ? root.width-column-monthly : root.width-column-monthly;
                                    background: i == return_row_data.length -1 ? root.bg-avg :
                                                value > 0 ? root.bg-increase : value < 0 ? root.bg-decrease : value == 0? #b3b0b0 : #222;
                                    Text {
                                        text: value + "%";
                                        color: root.text-item;
                                        horizontal-alignment: center;
                                    }
                                }
                            }
                        }
                    }
                }
            } 
        }
    }
}


export component ReturnMatrixTabBar{
    in property <[string]> tabs: ["Daily return(%)", "Weekly return(%)", "Monthly return(%)", "Quarterly return(%)"];
    in-out property <int> selected: 0;
    callback on_tab_selected(index: int);
    //local variables
    in property <color> bg-tab-selected: #9aa1a1;
    in property <color> bg-tab-unselected: #444 ;
    in property <color> bg-tab: #666;
    in property <length> padding-space: 4px;
    height: 40px;
    property <length> tab-min-width: 160px;
    property <length> tab-padding: 8px;
    property <length> tab-spacing: padding-space * 2;
    property <length> tabbar-width: tabs.length * tab-min-width + (tabs.length - 1) * tab-spacing + tab-padding * 2;
    Rectangle {
        width: root.tabbar-width;
        height: parent.height;
        background: bg-tab;
        border-radius: root.padding-space;
        HorizontalLayout {
            spacing: root.tab-spacing;
            alignment: start;
            width: parent.width;
            height: parent.height;
            padding-top: root.padding-space;
            padding-left: root.tab-padding;
            for tab[i] in root.tabs: Rectangle {
                height: parent.height - root.padding-space * 2;
                width: root.tab-min-width;
                background: i == root.selected ? root.bg-tab-selected : transparent;
                border-radius: root.padding-space;
                states [
                    hover when touch_area.has-hover: {
                        background: i == root.selected ? root.bg-tab-selected : root.bg-tab-unselected;
                    }
                ]
                text:= Text {
                    text: tab;
                    color: i == root.selected ? #fff : #e0e0e0;
                    font-size: 14px;
                    font-weight: 700;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }
                touch_area := TouchArea {
                    clicked => {
                        root.selected = i;
                        root.on_tab_selected(i);
                    }
                }
            }
        }
    }
}


export component ReturnComboBox {

    in-out property <int> current-index: 0;
    in-out property <string> current_value: "A-Z";
    property <bool> is_open: false;
    in property <[string]> model: ["Price ↑", "Price ↓", "A-Z"];

    // callback khi chọn item
    callback on_selected(index: int, text: string);
    height: 40px;
    // --- Nút chính (hiển thị item đang chọn) ---
    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 4px;
        border-width: 1px;
        background: #666;
    
        states [
            pressed when touch-area-sort.pressed: {
                background: #666.brighter(0.25);
            }
            hover when touch-area-sort.has-hover: {
                background: #666.brighter(0.5);
            }
        ]
        
        combo:= HorizontalLayout {
            padding-left: 10px;
            padding-right: 10px;

            Text {
                text: root.current-index >= 0 ? root.model[root.current-index] : "Chọn...";
                color: #ffffff;
                font-size: 14px;
                vertical-alignment: center;
                horizontal-alignment: left;
            }
            
            Rectangle { width: 10px; } // Spacer
            
            VerticalLayout {
                Rectangle {}
                Image {
                    width: root.height / 4;
                    height: root.height / 4;
                    source:@image-url("./../../image/up-arrow.svg");
                    colorize: #ffffff;
                }
                Image {
                    width: root.height / 4;
                    height: root.height / 4;
                    source: @image-url("./../../image/down-arrow.svg");
                    colorize: #ffffff;
                }
                Rectangle {}
            }
        }
        
        touch-area-sort := TouchArea {
            clicked => {
                is_open = !is_open;
            }
        }
        
        // Dropdown list
        if is_open: Rectangle {
            x: 0px;
            y: - (Math.min(model.length, 5) * 36px + 4px);
            width: Math.max(parent.width, 100px);
            height: Math.min(model.length, 5) * 36px;
            background: #2a2a2a;
            border-radius: 5px;
            border-width: 1px;
            border-color: #4a4a4a;
            drop-shadow-blur: 8px;
            drop-shadow-color: #00000060;
            drop-shadow-offset-y: -2px;
            clip: true;

            ScrollView {
                width: parent.width;
                height: parent.height;
                VerticalLayout {
                    spacing: 0;
                    for item[i] in root.model: Rectangle {
                        height: 36px;
                        background: i == root.current-index ? #444 : #222;
                        Text { text: item; color: white; x: 8px; y: 8px; font-size: 14px; }

                        states [
                            pressed when touch-area-item.pressed: {
                                background: #0c0c0c.brighter(0.5);
                            }
                            hover when touch-area-item.has-hover: {
                                background: #3d3d3d.brighter(0.25);
                            }
                        ]

                        touch-area-item := TouchArea {
                            clicked => {
                                root.current-index = i;
                                root.is_open = false;
                                root.on_selected(i, item);
                            }
                        }
                    }
                }
            }
        }
    }
}

export component QuantitativeReturnMatrix inherits Rectangle {
    width: 1300px;
    height: 800px;
    background: transparent;
    in-out property <int> selected_return_tab: 0;
    property <int> selected_month: 0;
    property <[string]> period_arr: ["daily", "weekly", "monthly", "quarterly"];
    property <[string]> month_arr: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    VerticalLayout {
        spacing: 2px;
        alignment: start;
        Rectangle {}
        HorizontalLayout {  
            spacing: 4px;
            alignment: start;
            
            ReturnComboBox {
                height: 40px;
                model: ["VNINDEX", "HNXINDEX","UPCOM", "VN30", "HNX30"];
                current-index: 0;
                on_selected(index, value) => {    
                    // Xử lý khi chọn item
                }
            }   

            if selected_return_tab == 0:  
                ReturnComboBox {
                    height: 40px;
                    model: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
                    current-index: 0;
                    on_selected(index, value) => {    
                        root.selected_month = index;
                    }
                } 
            Rectangle {}           
            ReturnMatrixTabBar {
                selected <=> root.selected_return_tab;
                on_tab_selected(index) => {
                    root.selected_return_tab = index;
                }
            }
            
        }
        
        Rectangle {
            vertical-stretch: 1;
            width: parent.width;
            height: parent.height - 50px;
            VerticalLayout {
                width: parent.width;
                alignment: start;
                
                ReturnMatrix {
                    return-type: period_arr[selected_return_tab];
                    selected-month: month_arr[selected_month];
                    x: 0;
                    visible: selected_return_tab == 0;
                }
            }
            VerticalLayout {
                width: parent.width;
                alignment: start;
                
                ReturnMatrix {
                    return-type: period_arr[selected_return_tab];
                    selected-month: month_arr[selected_month];
                    x: 0;
                    visible: selected_return_tab == 1;
                }
            }
            
            VerticalLayout {
                width: parent.width;
                alignment: start;
                
                ReturnMatrix {
                    return-type: period_arr[selected_return_tab];
                    selected-month: month_arr[selected_month];
                    x: 0;
                    visible: selected_return_tab == 2;
                }
            }
            VerticalLayout {
                width: parent.width;
                alignment: start;
                
                ReturnMatrix {
                    return-type: period_arr[selected_return_tab];
                    selected-month: month_arr[selected_month];
                    x: 0;
                    visible: selected_return_tab == 3;
                }
            }
        }

    }
}
